# Generated by Django 5.2.13 on 2026-05-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_department_alter_section_options_yearlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlevel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
