# Generated by Django 5.2.14 on 2026-05-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_yearlevel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['year_level__order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='yearlevel',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='yearlevel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='yearlevel',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
