# Generated by Django 5.2.14 on 2026-05-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_section_options_alter_yearlevel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentscore',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.schedule'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
